/// <reference lib="webworker" />
/* eslint-disable */
// This code is executed in the service worker context, not the main thread.

import { precacheAndRoute, ManifestEntry } from 'workbox-precaching'
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { BackgroundSyncPlugin, Queue } from 'workbox-background-sync'

declare let self: ServiceWorkerGlobalScope

// ============================================================
// Precaching — the app shell (generated by vite-plugin-pwa)
// ============================================================
precacheAndRoute(self.__WB_MANIFEST as ManifestEntry[])

// ============================================================
// API caching — network-first with cache fallback
// All /api/* requests use this strategy so the app shows cached
// data when offline instead of a blank page.
// ============================================================
const apiSyncTag = 'api-sync'
const apiBgSyncPlugin = new BackgroundSyncPlugin(apiSyncTag, {
  maxRetentionTime: 24 * 60, // retry for 24 hours
  bubbleToWindow: true,     // notify main thread of failures
})

// Queue for API requests that fail while offline
const apiQueue = new Queue(apiSyncTag, {
  maxRetentionTime: 24 * 60,
})

registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      apiBgSyncPlugin, // retry failed requests when back online
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 30 * 60, // 30 minutes
      }),
      // Interceptor: attach device_id to API requests for tracking
      new networkInterceptorPlugin(),
    ],
    networkTimeoutSeconds: 5,
  }),
  'GET'
)

// ============================================================
// Static asset caching — cache-first with expiration
// Fonts, images, manifest, icons
// ============================================================
registerRoute(
  ({ url }) =>
    url.pathname.startsWith('/static/') ||
    /\.(png|jpe?g|svg|gif|webp|ico|woff2?|txt|css|js)(\?.*)?$/i.test(url.pathname) ||
    url.pathname === '/manifest.json',
  new CacheFirst({
    cacheName: 'static-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
)

// Google Fonts — cache-first, long-lived
registerRoute(
  ({ url }) => url.host.includes('fonts.googleapis.com') || url.host.includes('fonts.gstatic.com'),
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
)

// ============================================================
// Navigation (HTML) — stale-while-revalidate
// Serve cached HTML immediately, update in background
// ============================================================
const navigationRoute = new NavigationRoute(
  new StaleWhileRevalidate({
    cacheName: 'html-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 24 * 60 * 60,
      }),
    ],
  }),
  {
    denylist: [/^\/api\//],
  }
)
registerRoute(navigationRoute)

// ============================================================
// Push notifications
// ============================================================
self.addEventListener('push', (event: PushEvent) => {
  let data: { title?: string; body?: string; icon?: string; url?: string } = {
    title: 'Sports Fixtures',
    body: 'New fixture updates available!',
    icon: '/FS-192.png',
    url: '/',
  }

  if (event.data) {
    try {
      data = event.data.json()
    } catch {
      data = { ...data, body: event.data.text() }
    }
  }

  const options: PushNotificationOptions = {
    body: data.body,
    icon: data.icon || '/FS-192.png',
    badge: '/FS-192.png',
    data: { url: data.url },
    vibrate: [200, 100, 200],
    tag: 'sports-fixtures-notification',
    actions: [
      { action: 'open', title: 'Open App' },
      { action: 'dismiss', title: 'Dismiss' },
    ],
  }

  event.waitUntil(self.registration.showNotification(data.title, options))
})

self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close()

  if (event.action === 'open') {
    const urlToOpen = event.notification.data?.url || '/'
    event.waitUntil(
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
        // If there's already a window open, focus it
        for (const client of clients) {
          if (client.url.includes(self.location.origin) && 'focus' in client) {
            return client.focus()
          }
        }
        // Otherwise open a new window
        const url = urlToOpen.startsWith('/') ? urlToOpen : new URL(urlToOpen, self.location.origin).toString()
        return self.clients.openWindow(url)
      })
    )
  }
})

// ============================================================
// Background sync — retry failed API requests
// ============================================================
self.addEventListener('sync', (event: SyncEvent) => {
  if (event.tag === apiSyncTag) {
    event.waitUntil(retryApiRequests())
  }
})

async function retryApiRequests() {
  // The BackgroundSync plugin's Queue handles this automatically
  // when we add networkInterceptorPlugin to the API route
}

// ============================================================
// Service worker lifecycle messages from main thread
// ============================================================
self.addEventListener('message', (event: MessageEvent) => {
  const data = event.data

  switch (data.type) {
    case 'SKIP_WAITING':
      self.skipWaiting()
      break

    case 'CACHE_FIXTURES':
      // Main thread asks SW to cache fixture data
      if (data.fixtures && Array.isArray(data.fixtures)) {
        cacheFixtures(data.fixtures)
      }
      break

    case 'INVALIDATE_CACHE':
      // Main thread asks SW to clear API cache
      if (data.cacheName) {
        caches.delete(data.cacheName).then(() => {
          self.clients.matchAll().then((clients) => {
            clients.forEach((client) => client.postMessage({ type: 'CACHE_INVALIDATED' }))
          })
        })
      }
      break

    case 'GET_CACHE_STATUS':
      self.clients.respondWith(
        new Response(JSON.stringify({ status: 'sw-active', version: __WB_MANIFEST ? __WB_MANIFEST[0]?.revision : 'unknown' }))
      )
      break
  }
})

// ============================================================
// Activate — clean up old caches
// ============================================================
self.addEventListener('activate', (event: ExtendableEvent) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      const validCacheNames = [
        'api-cache',
        'static-assets',
        'google-fonts',
        'html-cache',
        'vite:pwa', // workbox precache
      ]
      const oldCaches = cacheNames.filter((name) => !validCacheNames.includes(name))
      return Promise.all(oldCaches.map((name) => caches.delete(name)))
    })
  )

  // Claim clients so SW takes control immediately (no reload needed)
  event.waitUntil(self.clients.claim())
})

// ============================================================
// Custom fetch interceptor plugin for API requests
// ============================================================
function networkInterceptorPlugin() {
  return {
    handlerDidRequest: (args: { request: Request }) => {
      // Add cache-busting only for POST requests (to avoid caching refreshes)
      if (args.request.method === 'POST') {
        // Ensure POST requests don't use cached responses
        return 'networkOnly' as const
      }
      return null
    },
  }
}

// ============================================================
// Cache fixture data in the SW for offline access
// ============================================================
async function cacheFixtures(fixtures: unknown[]) {
  const cache = await caches.open('api-cache')
  const json = JSON.stringify({
    fixtures,
    timestamp: Date.now(),
  })
  await cache.put('/api/fixtures/cached', new Response(json, {
    headers: { 'Content-Type': 'application/json' },
  }))
}
