import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'
import { MotionConfig } from 'framer-motion'
import { registerSW, onUpdateAvailableCb, onUpdatedCb } from './lib/pwa'

// ACCESSIBILITY: honour the OS "reduce motion" setting. With reducedMotion="user",
// Framer Motion automatically skips/shortens animations for users who request it,
// preventing vestibular discomfort from the entrance/page transitions.

// Register the service worker (generated by vite-plugin-pwa).
// Callbacks for update detection — the main App component will consume these
// to show a "New version available" banner when the SW updates.
if (typeof window !== 'undefined') {
  registerSW()
  onUpdateAvailableCb(() => {
    console.log('[PWA] New version available — waiting for user to reload')
  })
  onUpdatedCb(() => {
    console.log('[PWA] Service worker activated')
  })
}

createRoot(document.getElementById('root')!).render(
  <MotionConfig reducedMotion="user">
    <App />
  </MotionConfig>
)
