/**
 * Service worker registration and update detection.
 *
 * Uses workbox-window to communicate with the service worker generated by
 * vite-plugin-pwa. Handles registration, update detection, and lifecycle events.
 */

export type UpdateStatus = 'unregistered' | 'registered' | 'update-available' | 'up-to-date' | 'error';

export interface PwaMessage {
  type: string;
  [key: string]: unknown;
}

let workbox: import('workbox-window').Workbox | null = null;

// Callbacks for update detection
let onUpdateAvailable: (() => void) | null = null;
let onUpdated: (() => void) | null = null;

/** Register the service worker with update detection. */
export function registerSW(): void {
  if (typeof window === 'undefined' || !('serviceWorker' in navigator)) {
    return;
  }

  try {
    workbox = new (window as any).Workbox('/sw.js');
  } catch {
    console.warn('[PWA] Service worker registration failed');
    return;
  }

  if (!workbox) return;

  workbox.addEventListener('installed', (event: any) => {
    if (event.isUpdate) {
      if (onUpdateAvailable) onUpdateAvailable();
    } else {
      if (onUpdated) onUpdated();
    }
  });

  workbox.addEventListener('waiting', () => {
    if (onUpdateAvailable) onUpdateAvailable();
  });

  workbox.addEventListener('controlling', () => {
    if (onUpdated) onUpdated();
  });

  workbox.register();
}

/** Set callback for when a new SW version is available. */
export function onUpdateAvailableCb(cb: (() => void) | null): void {
  onUpdateAvailable = cb;
}

/** Set callback for when SW is activated. */
export function onUpdatedCb(cb: (() => void) | null): void {
  onUpdated = cb;
}

/**
 * Ask the waiting service worker to take control.
 * Calls skipWaiting() + reloads the page.
 */
export function skipWaiting(): Promise<void> {
  if (!workbox) {
    return Promise.resolve();
  }

  return workbox.messageSW({ type: 'SKIP_WAITING' }).then((port) => {
    if (port) {
      port.addEventListener('message', () => {
        window.location.reload();
      });
    }

    // Fallback: reload after 2 seconds if message doesn't arrive
    setTimeout(() => {
      window.location.reload();
    }, 2000);
  });
}

/** Send a message to the service worker. */
export function postToSW(message: PwaMessage): void {
  if (!workbox) return;
  workbox.messageSW(message);
}

/** Check if the service worker is active. */
export function isSWActive(): boolean {
  if (!('serviceWorker' in navigator)) return false;
  return navigator.serviceWorker.controller !== null;
}

/** Get the current SW registration. */
export function getSWRegistration(): Promise<ServiceWorkerRegistration | null> {
  if (!('serviceWorker' in navigator)) return Promise.resolve(null);
  return navigator.serviceWorker.ready.then((reg) => reg || null);
}
